//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace SMSSendService.C6WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NetCallSoap", Namespace="http://xt.hnjiading.cn/")]
    public partial class NetCall : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendCallOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendC6CallOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserLoginCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NetCall() {
            this.Url = global::SMSSendService.Properties.Settings.Default.SMSSendService_C6WebService_NetCall;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendCallCompletedEventHandler sendCallCompleted;
        
        /// <remarks/>
        public event sendC6CallCompletedEventHandler sendC6CallCompleted;
        
        /// <remarks/>
        public event getUserLoginCodeCompletedEventHandler getUserLoginCodeCompleted;
        
        /// <remarks/>
        public event getUserNameCompletedEventHandler getUserNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xt.hnjiading.cn/sendCall", RequestNamespace="http://xt.hnjiading.cn/", ResponseNamespace="http://xt.hnjiading.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int sendCall(string receiver, string smsContent) {
            object[] results = this.Invoke("sendCall", new object[] {
                        receiver,
                        smsContent});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void sendCallAsync(string receiver, string smsContent) {
            this.sendCallAsync(receiver, smsContent, null);
        }
        
        /// <remarks/>
        public void sendCallAsync(string receiver, string smsContent, object userState) {
            if ((this.sendCallOperationCompleted == null)) {
                this.sendCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendCallOperationCompleted);
            }
            this.InvokeAsync("sendCall", new object[] {
                        receiver,
                        smsContent}, this.sendCallOperationCompleted, userState);
        }
        
        private void OnsendCallOperationCompleted(object arg) {
            if ((this.sendCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendCallCompleted(this, new sendCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xt.hnjiading.cn/sendC6Call", RequestNamespace="http://xt.hnjiading.cn/", ResponseNamespace="http://xt.hnjiading.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int sendC6Call(string receiver, string smsContent, string type) {
            object[] results = this.Invoke("sendC6Call", new object[] {
                        receiver,
                        smsContent,
                        type});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void sendC6CallAsync(string receiver, string smsContent, string type) {
            this.sendC6CallAsync(receiver, smsContent, type, null);
        }
        
        /// <remarks/>
        public void sendC6CallAsync(string receiver, string smsContent, string type, object userState) {
            if ((this.sendC6CallOperationCompleted == null)) {
                this.sendC6CallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendC6CallOperationCompleted);
            }
            this.InvokeAsync("sendC6Call", new object[] {
                        receiver,
                        smsContent,
                        type}, this.sendC6CallOperationCompleted, userState);
        }
        
        private void OnsendC6CallOperationCompleted(object arg) {
            if ((this.sendC6CallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendC6CallCompleted(this, new sendC6CallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xt.hnjiading.cn/getUserLoginCode", RequestNamespace="http://xt.hnjiading.cn/", ResponseNamespace="http://xt.hnjiading.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getUserLoginCode(string userCode) {
            object[] results = this.Invoke("getUserLoginCode", new object[] {
                        userCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUserLoginCodeAsync(string userCode) {
            this.getUserLoginCodeAsync(userCode, null);
        }
        
        /// <remarks/>
        public void getUserLoginCodeAsync(string userCode, object userState) {
            if ((this.getUserLoginCodeOperationCompleted == null)) {
                this.getUserLoginCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserLoginCodeOperationCompleted);
            }
            this.InvokeAsync("getUserLoginCode", new object[] {
                        userCode}, this.getUserLoginCodeOperationCompleted, userState);
        }
        
        private void OngetUserLoginCodeOperationCompleted(object arg) {
            if ((this.getUserLoginCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserLoginCodeCompleted(this, new getUserLoginCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://xt.hnjiading.cn/getUserName", RequestNamespace="http://xt.hnjiading.cn/", ResponseNamespace="http://xt.hnjiading.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getUserName(string userCode) {
            object[] results = this.Invoke("getUserName", new object[] {
                        userCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getUserNameAsync(string userCode) {
            this.getUserNameAsync(userCode, null);
        }
        
        /// <remarks/>
        public void getUserNameAsync(string userCode, object userState) {
            if ((this.getUserNameOperationCompleted == null)) {
                this.getUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserNameOperationCompleted);
            }
            this.InvokeAsync("getUserName", new object[] {
                        userCode}, this.getUserNameOperationCompleted, userState);
        }
        
        private void OngetUserNameOperationCompleted(object arg) {
            if ((this.getUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserNameCompleted(this, new getUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void sendCallCompletedEventHandler(object sender, sendCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void sendC6CallCompletedEventHandler(object sender, sendC6CallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendC6CallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendC6CallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getUserLoginCodeCompletedEventHandler(object sender, getUserLoginCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserLoginCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserLoginCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getUserNameCompletedEventHandler(object sender, getUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591